apiVersion: v1
kind: Service
metadata:
  name: {{ include "translations-refresher.fullname" . }}
  labels:
    {{- include "translations-refresher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "translations-refresher.selectorLabels" . | nindent 4 }}
